services:
  moment-template: &moment-template
    extends:
      file: base.yml
      service: gpu-model-base
    image: moment
    build:
      context: ../model-services/moment
      dockerfile: Dockerfile
    profiles: ["moment", "all-models"]

  moment-small:
    <<: *moment-template
    environment:
      - MODEL_ID=AutonLab/MOMENT-1-small

  moment-base-model:
    <<: *moment-template
    environment:
      - MODEL_ID=AutonLab/MOMENT-1-base

  moment-large:
    <<: *moment-template
    environment:
      - MODEL_ID=AutonLab/MOMENT-1-large
