services:
  tabpfn-ts:
    extends:
      file: base.yml
      service: gpu-model-base
    image: tabpfn-ts
    build:
      context: ../model-services/tabpfn-ts
      dockerfile: Dockerfile
    environment:
      - TABPFN_DISABLE_TELEMETRY=1
      - MAX_CONTEXT_LENGTH=4096
    profiles: ["tabpfn-ts", "all-models"]
